### ISSUE TITLE
Oprava úkolu

### ISSUE THREAD

**Issue by ifischerova** [Klatnik/Zivotopis#1]
Ahoj Katko, bezva práce 👍
Mám k tomu jen dvě drobnosti, to první je asi spíš tip a je na tobě, zda to upravíš. Názvy tříd prosím sjednoť. 

### index.html
- přehled kurzů a ostatních znalostí by bylo lepší řešit spíš jako seznam než odstavec se zalomenými řádky
- [x] názvy tříd by měly být jen v jednom jazyce - v tomto případě buď česky, nebo anglicky

**Comment by Klatnik** [comment]
Ahoj, názvy tříd opraveny, přidány i seznamy.

**Comment by ifischerova** [comment]
Ahoj Katko, dobrá práce 👍
